version: "3.7"

services:
    auth:
      container_name: authapache
      image: php:8.1-apache
      volumes:
        - ./:/var/www/html
        - ./apache/core.conf:/etc/apache2/apache2.conf
        - ./apache/default.conf:/etc/apache2/sites-available/000-default.conf
      ports:
        - 8080:80
      build:
        context: .
        dockerfile: Dockerfile

    authpg:
      container_name: authpg
      image: postgres:latest
      volumes:
        - ./postgres:/data/postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: pass
        PGDATA: /data/postgres

    authredis:
        image: redis:latest
        container_name: authredis
        restart: always
        ports:
          - "6379:6379"
        volumes:
          - /tmp/cache:/root/redis
        environment:
          - REDIS_PASSWORD=pass
          - REDIS_PORT=6379
          - REDIS_DATABASES=16
    
    adminer:
      container_name: adminer
      image: adminer:latest
      restart: always
      ports:
        - 8093:8080
      